### ISSUE TITLE
Can this work with custom media queries?

### ISSUE THREAD

**Issue by sloria** [jonathantneal/postcss-media-fn#1]
I am using cssnext, which includes postcss-custom-media. Is there a way to get this plugin to work well with postcss-custom-media, such that the `media()` can be passed a custom media query?

```css
@custom-media --break-lg (width >= 48em);

h1 {
  font-size: media(
    1em,
    (--break-lg) 1.125em
  )
}
```

Currently, `min-width: 48em` does *not* get properly substituted.
